# Generated by Django 4.1.4 on 2023-01-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_alter_advert_title'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_adverts',
            field=models.ManyToManyField(to='advert.advert'),
        ),
    ]
