# Generated by Django 4.1.4 on 2023-02-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_favorite_adverts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_realtor',
            field=models.BooleanField(default=False),
        ),
    ]
