# Generated by Django 4.1.4 on 2023-02-02 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='clients',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
