# Generated by Django 4.1.4 on 2023-02-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0006_alter_advert_address_alter_advert_floor_and_more'),
        ('users', '0005_alter_customuser_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite_adverts',
            field=models.ManyToManyField(blank=True, related_name='favorite_adverts', to='advert.advert', verbose_name='Избранные объявления'),
        ),
    ]
