# Generated by Django 4.1.4 on 2023-02-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_alter_advert_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='advert_type',
            field=models.CharField(choices=[('Квартира', 'Apartment'), ('Дом', 'House'), ('Земельный участок', 'Land')], default='Земельный участок', max_length=20),
        ),
        migrations.AddField(
            model_name='advert',
            name='city',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='advert',
            name='floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='street',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
