# Generated by Django 4.1.4 on 2023-02-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_advert_advert_type_advert_city_advert_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
