# Generated by Django 4.1.4 on 2023-02-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_advert_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='advert',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
